export const AUTOMATION_NAME_MAX_LENGTH = 200;
export const AUTOMATION_MESSAGE_MAX_LENGTH = 10_000;
export const AUTOMATION_TIMEZONE_MAX_LENGTH = 100;
export const MIN_AUTOMATION_INTERVAL_MS = 30_000;
