import { resolve } from "node:path";

import { z } from "zod/v4";

import { formatFrontmatter, parseFrontmatter } from "../../utils/frontmatter";
import {
  atomicWrite,
  resolveContainedPath,
  SafePathError,
} from "../../utils/safe-file";
import {
  buildWorkflowArtifactFrontmatter,
  type WorkflowArtifactWriteProvenance,
} from "./artifact-frontmatter";
import {
  WorkflowArtifactKindSchema,
  WorkflowStateManager,
  WorkflowUuidSchema,
  type WorkflowArtifactKind,
  type WorkflowState,
} from "./state";

export type { WorkflowArtifactWriteProvenance } from "./artifact-frontmatter";

export const SINGLE_FILE_ARTIFACT_PATHS = {
  RESEARCH: "RESEARCH.md",
  PRD: "PRD.md",
  SPEC: "SPEC.md",
  TASKS: "TASKS.md",
  HANDOFF_SUMMARY: "HANDOFF_SUMMARY.md",
  INTERACTIONS: "INTERACTIONS.md",
  FINAL_REPORT: "FINAL_REPORT.md",
} as const;

// INTERACTIONS.md is an archive/audit/handoff artifact only. Live question queue
// state is stored in SessionStoreState.pendingInteractions, never in this file.
export const ARCHIVE_ONLY_ARTIFACT_KINDS = ["INTERACTIONS"] as const;

export const SINGLE_FILE_ARTIFACT_KINDS = [
  "RESEARCH",
  "PRD",
  "SPEC",
  "TASKS",
  "HANDOFF_SUMMARY",
  "INTERACTIONS",
  "FINAL_REPORT",
] as const;

export const SingleFileWorkflowArtifactKindSchema = z.enum(
  SINGLE_FILE_ARTIFACT_KINDS,
);

export type SingleFileWorkflowArtifactKind = z.infer<
  typeof SingleFileWorkflowArtifactKindSchema
>;

export const VALID_ARTIFACT_KIND_LIST = WorkflowArtifactKindSchema.options.join(
  ", ",
);

const ARTIFACT_NAME_CONTROL_CHARACTER_PATTERN = /[\u0000-\u001f\u007f]/;

export const MULTI_FILE_ARTIFACT_KINDS = ["CRITIC_REPORT", "EVIDENCE"] as const;

export const MultiFileWorkflowArtifactKindSchema = z.enum(
  MULTI_FILE_ARTIFACT_KINDS,
);

export type MultiFileWorkflowArtifactKind = z.infer<
  typeof MultiFileWorkflowArtifactKindSchema
>;

const MULTI_FILE_ARTIFACT_DIRECTORIES = {
  CRITIC_REPORT: "critic-reports",
  EVIDENCE: "evidence",
} as const satisfies Record<MultiFileWorkflowArtifactKind, string>;

const ARTIFACT_CONTENT_BODY_SCHEMA = z.string().refine(
  (content) => !/^---[ \t]*(?:\r?\n|$)/.test(content.trimStart()),
  {
    message: "content must be markdown body only; workflow artifact frontmatter is generated by Specra",
  },
);

const ARTIFACT_NAME_SCHEMA = z.string().trim().min(1).refine(
  (name) => !ARTIFACT_NAME_CONTROL_CHARACTER_PATTERN.test(name),
  { message: "name must be a single-line artifact name without control characters" },
).refine(
  (name) => !name.includes("/") && !name.includes("\\"),
  { message: "name must be a file name, not a path" },
).refine(
  (name) => sanitizeArtifactName(name).length > 0,
  { message: "name must contain at least one safe filename character" },
);

export const WorkflowArtifactWriteInputSchema = z.union([
  z.strictObject({
    workflowId: WorkflowUuidSchema,
    kind: SingleFileWorkflowArtifactKindSchema,
    content: ARTIFACT_CONTENT_BODY_SCHEMA,
  }),
  z.strictObject({
    workflowId: WorkflowUuidSchema,
    kind: MultiFileWorkflowArtifactKindSchema,
    name: ARTIFACT_NAME_SCHEMA,
    content: ARTIFACT_CONTENT_BODY_SCHEMA,
  }),
]);

export type WorkflowArtifactWriteInput = z.infer<
  typeof WorkflowArtifactWriteInputSchema
>;

export interface WorkflowArtifactWriteResult {
  workflowId: string;
  kind: NonNullable<WorkflowArtifactWriteInput["kind"]>;
  path: string;
  absolutePath: string;
  state: WorkflowState;
}

export interface WorkflowArtifactRawReadResult {
  path: string;
  absolutePath: string;
  content: string;
}

export interface WorkflowArtifactReadResult {
  path: string;
  absolutePath: string;
  content: string;
  frontmatter: Record<string, string>;
  body: string;
}

export class ArtifactPathError extends Error {
  constructor(
    public readonly workflowId: string,
    public readonly artifactPath: string,
  ) {
    super(
      `Invalid artifact path for workflow ${workflowId}: ${artifactPath}. ` +
        "Artifact paths are system-assigned. Write single-file artifacts by kind only, " +
        "write multi-file artifacts by kind and name, and read multi-file artifacts by a returned path.",
    );
    this.name = "ArtifactPathError";
  }
}

export class WorkflowArtifactManager {
  constructor(
    private readonly workspaceRoot: string,
    private readonly stateManager = new WorkflowStateManager(workspaceRoot),
  ) {}

  async write(
    input: WorkflowArtifactWriteInput,
    provenance: WorkflowArtifactWriteProvenance = {},
  ): Promise<WorkflowArtifactWriteResult> {
    const parsed = WorkflowArtifactWriteInputSchema.parse(input);
    const path = deriveWorkflowArtifactPath(parsed);
    const absolutePath = await this.artifactPath(parsed.workflowId, path);
    this.assertAllowedArtifactPath(parsed.workflowId, parsed.kind, path);

    const state = await this.stateManager.read(parsed.workflowId);

    const content = formatFrontmatter(
      buildWorkflowArtifactFrontmatter({ kind: parsed.kind, path }, state, provenance),
      parsed.content,
    );
    await atomicWrite(absolutePath, content);

    const updated = await this.stateManager.updateArtifacts(
      parsed.workflowId,
      this.updateArtifacts(state.artifacts, parsed.kind, path),
    );

    return { workflowId: parsed.workflowId, kind: parsed.kind, path, absolutePath, state: updated };
  }

  async read(
    workflowId: string,
    artifactPath: string,
  ): Promise<WorkflowArtifactReadResult> {
    const raw = await this.readRaw(workflowId, artifactPath);
    const { absolutePath, content } = raw;
    const parsed = parseFrontmatter(content);
    return { path: artifactPath, absolutePath, content, ...parsed };
  }

  async readRaw(
    workflowId: string,
    artifactPath: string,
  ): Promise<WorkflowArtifactRawReadResult> {
    const absolutePath = await this.artifactPath(workflowId, artifactPath);
    const content = await Bun.file(absolutePath).text();
    return { path: artifactPath, absolutePath, content };
  }

  async readByKind(
    workflowId: string,
    kind: SingleFileWorkflowArtifactKind,
  ): Promise<WorkflowArtifactReadResult> {
    return await this.read(workflowId, deriveSingleFileArtifactPath(kind));
  }

  listPathsByKind(state: WorkflowState, kind: MultiFileWorkflowArtifactKind): string[] {
    const existing = state.artifacts[kind];
    if (!existing) return [];
    return Array.isArray(existing) ? existing : [existing];
  }

  private updateArtifacts(
    artifacts: WorkflowState["artifacts"],
    kind: NonNullable<WorkflowArtifactWriteInput["kind"]>,
    artifactPath: string,
  ): WorkflowState["artifacts"] {
    if (isMultiFileWorkflowArtifactKind(kind)) {
      const existing = artifacts[kind];
      const paths = Array.isArray(existing) ? existing : existing ? [existing] : [];
      return { ...artifacts, [kind]: [...new Set([...paths, artifactPath])] };
    }

    return { ...artifacts, [kind]: artifactPath };
  }

  private assertAllowedArtifactPath(
    workflowId: string,
    kind: WorkflowArtifactWriteInput["kind"],
    artifactPath: string,
  ): void {
    if (isSingleFileWorkflowArtifactKind(kind)) {
      if (artifactPath !== deriveSingleFileArtifactPath(kind)) {
        throw new ArtifactPathError(workflowId, artifactPath);
      }
      return;
    }

    if (isMultiFileWorkflowArtifactKind(kind) && artifactPath.startsWith(`${MULTI_FILE_ARTIFACT_DIRECTORIES[kind]}/`)) {
      return;
    }

    throw new ArtifactPathError(workflowId, artifactPath);
  }

  private async artifactPath(
    workflowId: string,
    artifactPath: string,
  ): Promise<string> {
    const workflowRoot = resolve(
      this.workspaceRoot,
      ".specra",
      "workflows",
      workflowId,
    );
    try {
      return await resolveContainedPath(artifactPath, workflowRoot);
    } catch (error) {
      if (error instanceof SafePathError) {
        throw new ArtifactPathError(workflowId, artifactPath);
      }
      throw error;
    }
  }

}

export function deriveSingleFileArtifactPath(kind: SingleFileWorkflowArtifactKind): string {
  return SINGLE_FILE_ARTIFACT_PATHS[kind];
}

export function deriveWorkflowArtifactPath(input: WorkflowArtifactWriteInput): string {
  if (!("name" in input)) {
    return deriveSingleFileArtifactPath(input.kind);
  }

  return `${MULTI_FILE_ARTIFACT_DIRECTORIES[input.kind]}/${sanitizeArtifactName(input.name)}.md`;
}

export function isSingleFileWorkflowArtifactKind(kind: WorkflowArtifactKind): kind is SingleFileWorkflowArtifactKind {
  return Object.hasOwn(SINGLE_FILE_ARTIFACT_PATHS, kind);
}

export function isMultiFileWorkflowArtifactKind(kind: WorkflowArtifactKind): kind is MultiFileWorkflowArtifactKind {
  return Object.hasOwn(MULTI_FILE_ARTIFACT_DIRECTORIES, kind);
}

function sanitizeArtifactName(name: string): string {
  const withoutMarkdownExtension = name.trim().replace(/\.md$/i, "");
  return withoutMarkdownExtension
    .replace(/\s+/g, "-")
    .replace(/[^A-Za-z0-9._-]/g, "")
    .replace(/^[-_.]+|[-_.]+$/g, "");
}
