import { resolve } from "node:path";

import { z } from "zod/v4";

import { formatFrontmatter, parseFrontmatter } from "../../utils/frontmatter";
import {
  atomicWrite,
  resolveContainedPath,
  SafePathError,
} from "../../utils/safe-file";
import {
  buildWorkflowArtifactFrontmatter,
  type WorkflowArtifactWriteProvenance,
} from "./artifact-frontmatter";
import {
  WorkflowArtifactKindSchema,
  WorkflowStateManager,
  WorkflowUuidSchema,
  type WorkflowState,
} from "./state";

export type { WorkflowArtifactWriteProvenance } from "./artifact-frontmatter";

export const SINGLE_FILE_ARTIFACT_PATHS = {
  RESEARCH: "RESEARCH.md",
  PRD: "PRD.md",
  SPEC: "SPEC.md",
  TASKS: "TASKS.md",
  HANDOFF_SUMMARY: "HANDOFF_SUMMARY.md",
  INTERACTIONS: "INTERACTIONS.md",
  FINAL_REPORT: "FINAL_REPORT.md",
} as const;

// INTERACTIONS.md is an archive/audit/handoff artifact only. Live question queue
// state is stored in SessionStoreState.pendingInteractions, never in this file.
export const ARCHIVE_ONLY_ARTIFACT_KINDS = ["INTERACTIONS"] as const;

export const SINGLE_FILE_ARTIFACT_KINDS = [
  "RESEARCH",
  "PRD",
  "SPEC",
  "TASKS",
  "HANDOFF_SUMMARY",
  "INTERACTIONS",
  "FINAL_REPORT",
] as const;

export const SingleFileWorkflowArtifactKindSchema = z.enum(
  SINGLE_FILE_ARTIFACT_KINDS,
);

export type SingleFileWorkflowArtifactKind = z.infer<
  typeof SingleFileWorkflowArtifactKindSchema
>;

export const VALID_ARTIFACT_KIND_LIST = WorkflowArtifactKindSchema.options.join(
  ", ",
);

const SUPPORTING_ARTIFACT_PREFIXES = ["notes/"] as const;
const ARTIFACT_PATH_CONTROL_CHARACTER_PATTERN = /[\u0000-\u001f\u007f]/;

function isSupportingArtifactPath(artifactPath: string): boolean {
  return SUPPORTING_ARTIFACT_PREFIXES.some((prefix) => artifactPath.startsWith(prefix));
}

function shouldAllowPlainArtifactBody(artifactPath: string): boolean {
  return (
    isSupportingArtifactPath(artifactPath) ||
    artifactPath.startsWith("evidence/") ||
    artifactPath.startsWith("critic-reports/")
  );
}

export const WorkflowArtifactWriteInputSchema = z.strictObject({
  workflowId: WorkflowUuidSchema,
  kind: WorkflowArtifactKindSchema.optional(),
  path: z.string().min(1).refine(
    (artifactPath) => !ARTIFACT_PATH_CONTROL_CHARACTER_PATTERN.test(artifactPath),
    { message: "path must be a single-line artifact path without control characters" },
  ),
  content: z.string().refine((content) => !/^---[ \t]*(?:\r?\n|$)/.test(content.trimStart()), {
    message: "content must be markdown body only; workflow artifact frontmatter is generated by Specra",
  }),
}).superRefine((input, ctx) => {
  if (input.kind || isSupportingArtifactPath(input.path)) return;

  ctx.addIssue({
    code: "custom",
    path: ["kind"],
    message: `kind is required unless path is under notes/. Valid kinds: ${VALID_ARTIFACT_KIND_LIST}`,
  });
});

export type WorkflowArtifactWriteInput = z.infer<
  typeof WorkflowArtifactWriteInputSchema
>;

export interface WorkflowArtifactWriteResult {
  path: string;
  absolutePath: string;
  state: WorkflowState;
}

export interface WorkflowArtifactRawReadResult {
  path: string;
  absolutePath: string;
  content: string;
}

export interface WorkflowArtifactReadResult {
  path: string;
  absolutePath: string;
  content: string;
  frontmatter: Record<string, string>;
  body: string;
}

export class ArtifactPathError extends Error {
  constructor(
    public readonly workflowId: string,
    public readonly artifactPath: string,
  ) {
    super(
      `Invalid artifact path for workflow ${workflowId}: ${artifactPath}. ` +
        `Valid kinds: ${VALID_ARTIFACT_KIND_LIST}. ` +
        "Allowed paths: RESEARCH.md, PRD.md, SPEC.md, TASKS.md, HANDOFF_SUMMARY.md, " +
        "INTERACTIONS.md, FINAL_REPORT.md, critic-reports/*.md, evidence/*, notes/*",
    );
    this.name = "ArtifactPathError";
  }
}

export class WorkflowArtifactManager {
  constructor(
    private readonly workspaceRoot: string,
    private readonly stateManager = new WorkflowStateManager(workspaceRoot),
  ) {}

  async write(
    input: WorkflowArtifactWriteInput,
    provenance: WorkflowArtifactWriteProvenance = {},
  ): Promise<WorkflowArtifactWriteResult> {
    const parsed = WorkflowArtifactWriteInputSchema.parse(input);
    const absolutePath = await this.artifactPath(parsed.workflowId, parsed.path);
    this.assertAllowedArtifactPath(parsed.workflowId, parsed.kind, parsed.path);

    const state = await this.stateManager.read(parsed.workflowId);

    const content = formatFrontmatter(
      buildWorkflowArtifactFrontmatter(parsed, state, provenance),
      parsed.content,
    );
    await atomicWrite(absolutePath, content);

    const updated = parsed.kind && !isSupportingArtifactPath(parsed.path)
      ? await this.stateManager.updateArtifacts(
          parsed.workflowId,
          this.updateArtifacts(state.artifacts, parsed.kind, parsed.path),
        )
      : state;

    return { path: parsed.path, absolutePath, state: updated };
  }

  async read(
    workflowId: string,
    artifactPath: string,
  ): Promise<WorkflowArtifactReadResult> {
    const raw = await this.readRaw(workflowId, artifactPath);
    const { absolutePath, content } = raw;
    const parsed = shouldAllowPlainArtifactBody(artifactPath) && !content.trimStart().startsWith("---")
      ? { frontmatter: {}, body: content }
      : parseFrontmatter(content);
    return { path: artifactPath, absolutePath, content, ...parsed };
  }

  async readRaw(
    workflowId: string,
    artifactPath: string,
  ): Promise<WorkflowArtifactRawReadResult> {
    const absolutePath = await this.artifactPath(workflowId, artifactPath);
    const content = await Bun.file(absolutePath).text();
    return { path: artifactPath, absolutePath, content };
  }

  async readByKind(
    workflowId: string,
    kind: SingleFileWorkflowArtifactKind,
  ): Promise<WorkflowArtifactReadResult> {
    return await this.read(workflowId, SINGLE_FILE_ARTIFACT_PATHS[kind]);
  }

  private updateArtifacts(
    artifacts: WorkflowState["artifacts"],
    kind: NonNullable<WorkflowArtifactWriteInput["kind"]>,
    artifactPath: string,
  ): WorkflowState["artifacts"] {
    if (kind === "CRITIC_REPORT" || kind === "EVIDENCE") {
      const existing = artifacts[kind];
      const paths = Array.isArray(existing) ? existing : existing ? [existing] : [];
      return { ...artifacts, [kind]: [...new Set([...paths, artifactPath])] };
    }

    return { ...artifacts, [kind]: artifactPath };
  }

  private assertAllowedArtifactPath(
    workflowId: string,
    kind: WorkflowArtifactWriteInput["kind"],
    artifactPath: string,
  ): void {
    if (isSupportingArtifactPath(artifactPath)) {
      return;
    }

    if (!kind) {
      throw new ArtifactPathError(workflowId, artifactPath);
    }

    if (kind in SINGLE_FILE_ARTIFACT_PATHS) {
      if (
        artifactPath !==
        SINGLE_FILE_ARTIFACT_PATHS[
          kind as keyof typeof SINGLE_FILE_ARTIFACT_PATHS
        ]
      ) {
        throw new ArtifactPathError(workflowId, artifactPath);
      }
      return;
    }

    if (kind === "CRITIC_REPORT" && /^critic-reports\/.+\.md$/.test(artifactPath)) {
      return;
    }

    if (kind === "EVIDENCE" && artifactPath.startsWith("evidence/")) {
      return;
    }

    throw new ArtifactPathError(workflowId, artifactPath);
  }

  private async artifactPath(
    workflowId: string,
    artifactPath: string,
  ): Promise<string> {
    const workflowRoot = resolve(
      this.workspaceRoot,
      ".specra",
      "workflows",
      workflowId,
    );
    try {
      return await resolveContainedPath(artifactPath, workflowRoot);
    } catch (error) {
      if (error instanceof SafePathError) {
        throw new ArtifactPathError(workflowId, artifactPath);
      }
      throw error;
    }
  }

}
