import {
  EXPLORER_READ_ONLY_TOOLS,
  SKILL_TOOLS,
  DELEGATION_EXECUTION_TOOLS,
} from "../../tools/groups";
import {
  TOOL_ARTIFACT_READ,
  TOOL_ARTIFACT_WRITE,
  TOOL_ASK_USER,
  TOOL_AST_GREP_REPLACE,
  TOOL_BASH,
  TOOL_FILE_EDIT,
  TOOL_FILE_WRITE,
  TOOL_MEMORY_READ,
  TOOL_MEMORY_WRITE,
  TOOL_TODO_WRITE,
  TOOL_WORKFLOW_READ,
  TOOL_WORKFLOW_PROPOSE_INTERACTIONS,
  TOOL_WORKFLOW_TASK_CHECK,
} from "../../tools/names";

const WORKFLOW_ARTIFACT_AUTHOR_TOOLS = [TOOL_WORKFLOW_READ, TOOL_ARTIFACT_WRITE, TOOL_WORKFLOW_PROPOSE_INTERACTIONS] as const;
const WORKFLOW_TASK_CHECK_TOOLS = [TOOL_ARTIFACT_READ, TOOL_WORKFLOW_READ, TOOL_WORKFLOW_TASK_CHECK] as const;
const ARTIFACT_EVIDENCE_WRITE_TOOLS = [TOOL_ARTIFACT_WRITE] as const;

const NON_INTERACTIVE_EXPLORER_READ_ONLY_TOOLS = EXPLORER_READ_ONLY_TOOLS.filter((tool) => tool !== TOOL_ASK_USER);
const TODO_ONLY_TOOLS = [TOOL_TODO_WRITE] as const;
const TODO_AND_ASK_TOOLS = [TOOL_ASK_USER, TOOL_TODO_WRITE] as const;
const MEMORY_READ_TOOLS = [TOOL_MEMORY_READ] as const;
const MEMORY_WRITE_TOOLS = [TOOL_MEMORY_READ, TOOL_MEMORY_WRITE] as const;
const SOURCE_WRITE_TOOLS = [TOOL_FILE_WRITE, TOOL_FILE_EDIT, TOOL_BASH, TOOL_AST_GREP_REPLACE] as const;

function uniqueTools<const T extends readonly string[]>(tools: T): readonly T[number][] {
  return [...new Set(tools)] as readonly T[number][];
}

export const workflowRoleToolPermissions = {
  product: uniqueTools([
    ...WORKFLOW_ARTIFACT_AUTHOR_TOOLS,
    ...NON_INTERACTIVE_EXPLORER_READ_ONLY_TOOLS,
    ...DELEGATION_EXECUTION_TOOLS,
    ...TODO_ONLY_TOOLS,
    ...SKILL_TOOLS,
  ]),
  spec: uniqueTools([
    ...WORKFLOW_ARTIFACT_AUTHOR_TOOLS,
    ...NON_INTERACTIVE_EXPLORER_READ_ONLY_TOOLS,
    ...DELEGATION_EXECUTION_TOOLS,
    ...TODO_ONLY_TOOLS,
    ...SKILL_TOOLS,
  ]),
  critic: uniqueTools([
    ...WORKFLOW_ARTIFACT_AUTHOR_TOOLS,
    ...NON_INTERACTIVE_EXPLORER_READ_ONLY_TOOLS,
    ...DELEGATION_EXECUTION_TOOLS,
    ...TODO_ONLY_TOOLS,
    ...SKILL_TOOLS,
  ]),
  foreman: uniqueTools([
    ...WORKFLOW_TASK_CHECK_TOOLS,
    ...EXPLORER_READ_ONLY_TOOLS,
    ...DELEGATION_EXECUTION_TOOLS,
    ...TODO_AND_ASK_TOOLS,
    ...SKILL_TOOLS,
  ]),
  builder: uniqueTools([
    ...EXPLORER_READ_ONLY_TOOLS,
    ...SOURCE_WRITE_TOOLS,
    ...DELEGATION_EXECUTION_TOOLS,
    ...TODO_AND_ASK_TOOLS,
    ...MEMORY_WRITE_TOOLS,
    ...ARTIFACT_EVIDENCE_WRITE_TOOLS,
    ...SKILL_TOOLS,
  ]),
  reviewer: uniqueTools([
    ...EXPLORER_READ_ONLY_TOOLS,
    ...DELEGATION_EXECUTION_TOOLS,
    ...ARTIFACT_EVIDENCE_WRITE_TOOLS,
    ...TODO_AND_ASK_TOOLS,
    ...MEMORY_READ_TOOLS,
    ...SKILL_TOOLS,
  ]),
  librarian: uniqueTools([
    ...EXPLORER_READ_ONLY_TOOLS,
    ...MEMORY_READ_TOOLS,
    ...SKILL_TOOLS,
    TOOL_ASK_USER,
  ]),
} as const;

export type WorkflowRoleName = keyof typeof workflowRoleToolPermissions;
