import {
  DELEGATION_CORE_TOOLS,
  DEFAULT_SUB_AGENT_TIMEOUT_MS,
  MAX_CONCURRENT_SUB_AGENTS,
  SKILL_ACCESS_TOOLS,
} from "../constants";
import type { AgentDefinition } from "../factory-types";
import { leadRoleContract } from "./role-contracts";
import {
  TOOL_ASK_USER,
  TOOL_AUTOMATION_CREATE,
  TOOL_AST_GREP_REPLACE,
  TOOL_AST_GREP_SEARCH,
  TOOL_BASH,
  TOOL_CANCEL_SESSION,
  TOOL_COMPRESS,
  TOOL_CREATE_GOAL,
  TOOL_FILE_EDIT,
  TOOL_FILE_READ,
  TOOL_FILE_WRITE,
  TOOL_GET_GOAL,
  TOOL_GIT_DIFF,
  TOOL_GIT_STATUS,
  TOOL_GLOB,
  TOOL_GREP,
  TOOL_LSP_DIAGNOSTICS,
  TOOL_LSP_FIND_REFERENCES,
  TOOL_LSP_GOTO_DEFINITION,
  TOOL_LSP_SYMBOLS,
  TOOL_MEMORY_READ,
  TOOL_MEMORY_WRITE,
  TOOL_OUTPUT_READ,
  TOOL_OUTPUT_SEARCH,
  TOOL_PROJECT_TODO_UPDATE,
  TOOL_TODO_WRITE,
  TOOL_UPDATE_GOAL,
  TOOL_WEB_FETCH,
} from "../../tools/names";

export const leadAgentDefinition = {
  name: "lead",
  displayName: "Lead",
  profiles: ["principal"],
  roleContract: leadRoleContract,
  tools: {
    tools: [
      TOOL_FILE_READ,
      TOOL_FILE_WRITE,
      TOOL_FILE_EDIT,
      TOOL_GREP,
      TOOL_GLOB,
      TOOL_AST_GREP_SEARCH,
      TOOL_AST_GREP_REPLACE,
      TOOL_GIT_STATUS,
      TOOL_GIT_DIFF,
      TOOL_BASH,
      TOOL_TODO_WRITE,
      TOOL_ASK_USER,
      TOOL_LSP_DIAGNOSTICS,
      TOOL_LSP_GOTO_DEFINITION,
      TOOL_LSP_FIND_REFERENCES,
      TOOL_LSP_SYMBOLS,
      TOOL_WEB_FETCH,
      ...DELEGATION_CORE_TOOLS,
      TOOL_CANCEL_SESSION,
      TOOL_OUTPUT_READ,
      TOOL_OUTPUT_SEARCH,
      TOOL_COMPRESS,
      TOOL_MEMORY_READ,
      TOOL_MEMORY_WRITE,
      TOOL_CREATE_GOAL,
      TOOL_GET_GOAL,
      TOOL_UPDATE_GOAL,
      TOOL_AUTOMATION_CREATE,
      TOOL_PROJECT_TODO_UPDATE,
      ...SKILL_ACCESS_TOOLS,
    ],
    delegateTargets: ["analyst", "build", "explore", "librarian"],
  },
  mcpTools: ["context7", "exa"],
  hooks: {
    autoCompact: true,
    autoInjectReminder: true,
    todoStepReminder: true,
    todoQueryLoopContinuation: true,
    memoryExtraction: true,
    memoryConsolidation: true,
    titleGeneration: "enabled",
  },
  childPolicy: {
    maxDepth: 3,
    maxConcurrent: MAX_CONCURRENT_SUB_AGENTS,
    timeoutMs: DEFAULT_SUB_AGENT_TIMEOUT_MS,
    abortCascade: true,
    terminalReminders: true,
  },
  includeMemoryInPrompt: true,
  skills: [
    "orchestrate-work",
    "plan-work",
    "run-goal",
    "shape-todo",
    "review-work",
    "git-master",
    "safe-refactor",
    "codemap",
    "research-docs",
    "automation-create",
  ],
} as const satisfies AgentDefinition;

/** Contextual capability projection for a Todo-bound root Lead Discussion. */
export const DISCUSSION_LEAD_TOOL_NAMES = [
  TOOL_FILE_READ,
  TOOL_GREP,
  TOOL_GLOB,
  TOOL_AST_GREP_SEARCH,
  TOOL_GIT_STATUS,
  TOOL_GIT_DIFF,
  TOOL_BASH,
  TOOL_TODO_WRITE,
  TOOL_ASK_USER,
  TOOL_LSP_DIAGNOSTICS,
  TOOL_LSP_GOTO_DEFINITION,
  TOOL_LSP_FIND_REFERENCES,
  TOOL_LSP_SYMBOLS,
  TOOL_WEB_FETCH,
  TOOL_MEMORY_READ,
  TOOL_MEMORY_WRITE,
  TOOL_PROJECT_TODO_UPDATE,
  ...DELEGATION_CORE_TOOLS,
  TOOL_OUTPUT_READ,
  TOOL_OUTPUT_SEARCH,
  TOOL_COMPRESS,
  ...SKILL_ACCESS_TOOLS,
] as const;

export const DISCUSSION_LEAD_DELEGATE_TARGETS = ["explore", "librarian"] as const;

/** Effective delegation depth for a Todo-bound Lead, derived from its live binding. */
export const DISCUSSION_LEAD_MAX_DEPTH = 2;
