/// <reference types="bun" />

import type { BunPlugin } from "bun";
import { readdir, stat } from "node:fs/promises";
import { dirname, extname, join, relative, sep } from "node:path";

const rootDir = join(import.meta.dir, "..");
const webDistDir = join(rootDir, "apps", "web", "dist");
const manifestPath = join(rootDir, "apps", "server", "src", "web-manifest.ts");
const cssTreePatchPath = join(rootDir, "node_modules", "css-tree", "data", "patch.json");
const cssTreePackagePath = join(rootDir, "node_modules", "css-tree", "package.json");

async function collectFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const fullPath = join(dir, entry.name);
      if (entry.isDirectory()) {
        return collectFiles(fullPath);
      }

      if (entry.isFile() && extname(entry.name) !== ".map") {
        return [fullPath];
      }

      return [];
    }),
  );

  return files.flat().sort((a, b) => a.localeCompare(b));
}

function toPosixPath(path: string): string {
  return path.split(sep).join("/");
}

function toRequestPath(assetPath: string): string {
  const relativePath = toPosixPath(relative(webDistDir, assetPath));
  return relativePath === "index.html" ? "/index.html" : `/${relativePath}`;
}

function toManifestImportPath(assetPath: string): string {
  const importPath = toPosixPath(relative(dirname(manifestPath), assetPath));
  return importPath.startsWith(".") ? importPath : `./${importPath}`;
}

async function generateManifest(): Promise<void> {
  const indexStat = await stat(join(webDistDir, "index.html")).catch(() => undefined);
  if (!indexStat?.isFile()) {
    throw new Error("apps/web/dist/index.html is missing. Run the Vite build before compiling.");
  }

  const files = await collectFiles(webDistDir);
  const imports = files.map(
    (file, index) => `import file_${index} from ${JSON.stringify(toManifestImportPath(file))} with { type: "file" };`,
  );
  const entries = files.map((file, index) => {
    const requestPath = toRequestPath(file);
    return `  [${JSON.stringify(requestPath)}, file_${index}],`;
  });

  const contents = [
    "// This file is generated by scripts/build.ts. Do not edit by hand.",
    "// @ts-nocheck",
    ...imports,
    "",
    "export const embeddedWebAssets = new Map<string, string>([",
    ...entries,
    "]);",
    "",
    "export const embeddedIndexPath = embeddedWebAssets.get(\"/index.html\");",
    "",
  ].join("\n");

  await Bun.write(manifestPath, contents);
  console.log(`Generated manifest with ${files.length} assets`);
}

async function runWebBuild(): Promise<void> {
  const proc = Bun.spawn(["bun", "run", "--cwd", "apps/web", "build"], {
    cwd: rootDir,
    stdout: "inherit",
    stderr: "inherit",
  });
  const exitCode = await proc.exited;
  if (exitCode !== 0) {
    throw new Error(`Vite build failed with exit code ${exitCode}`);
  }
}

async function compileBinary(): Promise<void> {
  const cssTreePatchJson = await Bun.file(cssTreePatchPath).text();
  const cssTreePackage = JSON.parse(await Bun.file(cssTreePackagePath).text()) as { version?: string };
  const cssTreePatchPlugin: BunPlugin = {
    name: "inline-css-tree-data-patch",
    setup(build) {
      build.onLoad({ filter: /css-tree\/lib\/data-patch\.js$/ }, () => ({
        contents: `export default ${cssTreePatchJson};\n`,
        loader: "js",
      }));
      build.onLoad({ filter: /css-tree\/lib\/version\.js$/ }, () => ({
        contents: `export const version = ${JSON.stringify(cssTreePackage.version ?? "0.0.0")};\n`,
        loader: "js",
      }));
    },
  };

  const entrypoint = join(rootDir, "apps", "server", "src", "main.ts");
  const outfile = join(rootDir, "dist", "specra");

  const result = await Bun.build({
    entrypoints: [entrypoint],
    outdir: join(rootDir, "dist"),
    naming: "[name].[ext]",
    minify: true,
    target: "bun",
    compile: true,
    plugins: [cssTreePatchPlugin],
  });

  if (!result.success) {
    for (const log of result.logs) {
      console.error(log);
    }
    throw new Error(`Bun.build() failed with ${result.logs.length} errors`);
  }

  const builtBinary = join(rootDir, "dist", "main");
  if (builtBinary !== outfile) {
    const { rename } = await import("node:fs/promises");
    await rename(builtBinary, outfile);
  }

  const bundleArtifact = join(rootDir, "dist", "main.js");
  await Bun.file(bundleArtifact).exists() && await import("node:fs/promises").then((fs) => fs.unlink(bundleArtifact));
}

await runWebBuild();
await generateManifest();
await compileBinary();
