/// <reference types="bun" />

import type { BunPlugin } from "bun";
import { mkdir, readdir, rm, stat } from "node:fs/promises";
import { dirname, extname, join, relative, sep } from "node:path";
import { readReleaseVersion } from "./release";

const rootDir = join(import.meta.dir, "..");
const webDistDir = join(rootDir, "apps", "web", "dist");
const buildTempDir = join(rootDir, "dist", ".build");
const buildEntrypointPath = join(buildTempDir, "main.ts");
const serverMainPath = join(rootDir, "apps", "server", "src", "main.ts");
const cssTreePatchPath = join(rootDir, "node_modules", "css-tree", "data", "patch.json");
const cssTreePackagePath = join(rootDir, "node_modules", "css-tree", "package.json");
const jsdomDefaultStyleSheetPath = join(rootDir, "node_modules", "jsdom", "lib", "jsdom", "browser", "default-stylesheet.css");
const jsdomComputedStylePath = join(rootDir, "node_modules", "jsdom", "lib", "jsdom", "living", "css", "helpers", "computed-style.js");
const supportedBuildTargets = new Set([
  "bun-darwin-arm64",
  "bun-darwin-x64",
  "bun-linux-arm64",
  "bun-linux-x64-baseline",
]);

async function collectFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const fullPath = join(dir, entry.name);
      if (entry.isDirectory()) {
        return collectFiles(fullPath);
      }

      if (entry.isFile() && extname(entry.name) !== ".map") {
        return [fullPath];
      }

      return [];
    }),
  );

  return files.flat().sort((a, b) => a.localeCompare(b));
}

function toPosixPath(path: string): string {
  return path.split(sep).join("/");
}

function toRequestPath(assetPath: string): string {
  const relativePath = toPosixPath(relative(webDistDir, assetPath));
  return relativePath === "index.html" ? "/index.html" : `/${relativePath}`;
}

function toBuildImportPath(path: string): string {
  const importPath = toPosixPath(relative(dirname(buildEntrypointPath), path));
  return importPath.startsWith(".") ? importPath : `./${importPath}`;
}

function readBuildTarget(): Bun.Build.CompileTarget | undefined {
  const target = Bun.env.ARCHCODE_BUILD_TARGET;
  if (!target) {
    return undefined;
  }
  if (!supportedBuildTargets.has(target)) {
    throw new Error(
      `Unsupported ARCHCODE_BUILD_TARGET ${JSON.stringify(target)}. ` +
      `Expected one of: ${[...supportedBuildTargets].join(", ")}`,
    );
  }
  return target as Bun.Build.CompileTarget;
}

async function writeProductionEntrypoint(version: string): Promise<void> {
  const indexStat = await stat(join(webDistDir, "index.html")).catch(() => undefined);
  if (!indexStat?.isFile()) {
    throw new Error("apps/web/dist/index.html is missing. Run the Vite build before compiling.");
  }

  const files = await collectFiles(webDistDir);
  const imports = files.map(
    (file, index) => `import file_${index} from ${JSON.stringify(toBuildImportPath(file))} with { type: "file" };`,
  );
  const entries = files.map((file, index) => {
    const requestPath = toRequestPath(file);
    return `  [${JSON.stringify(requestPath)}, file_${index}],`;
  });

  const contents = [
    "// AUTO-GENERATED by scripts/build.ts during `bun run build`.",
    "// This temporary production entrypoint is removed after compilation.",
    `import { startProductionArchCode } from ${JSON.stringify(toBuildImportPath(serverMainPath))};`,
    ...imports,
    "",
    "const embeddedWebAssets = new Map<string, string>([",
    ...entries,
    "]);",
    "",
    "startProductionArchCode(embeddedWebAssets, {",
    "  args: Bun.argv.slice(2),",
    `  version: ${JSON.stringify(version)},`,
    "});",
    "",
  ].join("\n");

  await mkdir(buildTempDir, { recursive: true });
  await Bun.write(buildEntrypointPath, contents);
  console.log(`Generated temporary production entrypoint with ${files.length} assets`);
}

async function runWebBuild(): Promise<void> {
  const proc = Bun.spawn(["bun", "run", "--cwd", "apps/web", "build"], {
    cwd: rootDir,
    stdout: "inherit",
    stderr: "inherit",
  });
  const exitCode = await proc.exited;
  if (exitCode !== 0) {
    throw new Error(`Vite build failed with exit code ${exitCode}`);
  }
}

async function compileBinary(buildTarget: Bun.Build.CompileTarget | undefined): Promise<void> {
  // Guard: verify css-tree package exists in node_modules
  const cssTreePackageExists = await Bun.file(cssTreePackagePath).exists();
  if (!cssTreePackageExists) {
    throw new Error(
      "css-tree package not found at node_modules/css-tree/. " +
      "Run `bun install` to ensure all dependencies are installed.",
    );
  }

  // Guard: verify jsdom exists and load its default stylesheet contents.
  // jsdom reads this CSS file via fs.readFileSync at module top-level using a
  // path resolved relative to __dirname. When compiled into a Bun binary,
  // __dirname points into the original build path, so the binary breaks when
  // distributed to a different machine or path. We inline the CSS so the
  // binary is self-contained.
  const jsdomStyleSheetExists = await Bun.file(jsdomDefaultStyleSheetPath).exists();
  if (!jsdomStyleSheetExists) {
    throw new Error(
      "jsdom default stylesheet not found at node_modules/jsdom/lib/jsdom/browser/default-stylesheet.css. " +
      "Run `bun install` to ensure all dependencies are installed.",
    );
  }
  const jsdomComputedStyleExists = await Bun.file(jsdomComputedStylePath).exists();
  if (!jsdomComputedStyleExists) {
    throw new Error(
      "jsdom computed-style.js not found at node_modules/jsdom/lib/jsdom/living/css/helpers/computed-style.js. " +
      "If jsdom was upgraded and this file moved, update the path in scripts/build.ts.",
    );
  }
  const jsdomDefaultStyleSheetContents = await Bun.file(jsdomDefaultStyleSheetPath).text();

  const cssTreePatchJson = await Bun.file(cssTreePatchPath).text();
  const cssTreePackage = JSON.parse(await Bun.file(cssTreePackagePath).text()) as { version?: string };

  // Guard: verify css-tree data.js patch target strings still exist
  // If css-tree is updated and these strings change, the patch is stale
  // and needs to be updated in this file.
  const cssTreeDataJsPath = join(rootDir, "node_modules", "css-tree", "lib", "data.js");
  const cssTreeDataJsSource = await Bun.file(cssTreeDataJsPath).text();
  const requiredStrings = [
    "import { createRequire } from 'module';",
    "const require = createRequire(import.meta.url);",
    "const mdnAtrules = require('mdn-data/css/at-rules.json');",
    "const mdnProperties = require('mdn-data/css/properties.json');",
    "const mdnSyntaxes = require('mdn-data/css/syntaxes.json');",
  ];
  for (const s of requiredStrings) {
    if (!cssTreeDataJsSource.includes(s)) {
      throw new Error(
        `css-tree patch target not found in node_modules/css-tree/lib/data.js.\n` +
        `Missing string: ${JSON.stringify(s)}\n\n` +
        `This usually means css-tree was updated. Check the css-tree source and update the patch ` +
        `string(s) in scripts/build.ts to match the new version (${cssTreePackage.version ?? "unknown"}).`,
      );
    }
  }

  const cssTreePatchPlugin: BunPlugin = {
    name: "inline-css-tree-data-patch",
    setup(build) {
      build.onLoad({ filter: /css-tree\/lib\/data\.js$/ }, async (args) => {
        const source = await Bun.file(args.path).text();
        const contents = source
          .replace(
            "import { createRequire } from 'module';\n",
            [
              "import mdnAtrules from 'mdn-data/css/at-rules.json' with { type: 'json' };",
              "import mdnProperties from 'mdn-data/css/properties.json' with { type: 'json' };",
              "import mdnSyntaxes from 'mdn-data/css/syntaxes.json' with { type: 'json' };",
              "",
            ].join("\n"),
          )
          .replace("const require = createRequire(import.meta.url);\n", "")
          .replace("const mdnAtrules = require('mdn-data/css/at-rules.json');\n", "")
          .replace("const mdnProperties = require('mdn-data/css/properties.json');\n", "")
          .replace("const mdnSyntaxes = require('mdn-data/css/syntaxes.json');\n", "");

        return { contents, loader: "js" };
      });
      build.onLoad({ filter: /css-tree\/lib\/syntax\/config\/lexer\.js$/ }, async (args) => {
        const source = await Bun.file(args.path).text();
        const dataImportPath = toPosixPath(relative(
          dirname(args.path),
          join(rootDir, "node_modules", "css-tree", "lib", "data.js"),
        ));
        const contents = source.replace(
          "import definitions from '../../data.js';",
          `import definitions from ${JSON.stringify(dataImportPath)};`,
        );

        return { contents, loader: "js" };
      });
      build.onLoad({ filter: /css-tree\/lib\/data-patch\.js$/ }, () => ({
        contents: `export default ${cssTreePatchJson};\n`,
        loader: "js",
      }));
      build.onLoad({ filter: /css-tree\/lib\/version\.js$/ }, () => ({
        contents: `export const version = ${JSON.stringify(cssTreePackage.version ?? "0.0.0")};\n`,
        loader: "js",
      }));
      build.onLoad({ filter: /jsdom\/lib\/jsdom\/living\/css\/helpers\/computed-style\.js$/ }, async (args) => {
        const source = await Bun.file(args.path).text();
        const contents = source.replace(
          /const defaultStyleSheet = fs\.readFileSync\([\s\S]*?\);\n/,
          `const defaultStyleSheet = ${JSON.stringify(jsdomDefaultStyleSheetContents)};\n`,
        );
        return { contents, loader: "js" };
      });
    },
  };

  const outfile = join(rootDir, "dist", "archcode");

  const result = await Bun.build({
    entrypoints: [buildEntrypointPath],
    minify: true,
    target: "bun",
    compile: {
      ...(buildTarget ? { target: buildTarget } : {}),
      outfile,
    },
    plugins: [cssTreePatchPlugin],
  });

  if (!result.success) {
    for (const log of result.logs) {
      console.error(log);
    }
    throw new Error(`Bun.build() failed with ${result.logs.length} errors`);
  }

  const bundleArtifact = join(rootDir, "dist", "main.js");
  await Bun.file(bundleArtifact).exists() && await import("node:fs/promises").then((fs) => fs.unlink(bundleArtifact));
}

await rm(buildTempDir, { recursive: true, force: true });
try {
  const version = await readReleaseVersion();
  const buildTarget = readBuildTarget();
  await runWebBuild();
  await writeProductionEntrypoint(version);
  await compileBinary(buildTarget);
} finally {
  await rm(buildTempDir, { recursive: true, force: true });
}
