export const TOOL_OUTPUT_PREVIEW_MAX_BYTES = 50 * 1024;
export const TOOL_OUTPUT_PREVIEW_MAX_LINES = 2_000;

export const TOOL_OUTPUT_ARTIFACT_MAX_BYTES = 64 * 1024 * 1024;
export const TOOL_OUTPUT_ARTIFACT_HEAD_MAX_BYTES = 63 * 1024 * 1024;
export const TOOL_OUTPUT_ARTIFACT_TAIL_MAX_BYTES = 1 * 1024 * 1024;

export const TOOL_OUTPUT_BODY_QUOTA_BYTES = 500 * 1024 * 1024;
export const TOOL_OUTPUT_BODY_MAX_ACTIVE = 10_000;
export const TOOL_OUTPUT_LEDGER_MAX_ENTRIES = 100_000;
export const TOOL_OUTPUT_LEDGER_MAX_BYTES = 64 * 1024 * 1024;
export const TOOL_OUTPUT_BODY_TTL_MS = 7 * 24 * 60 * 60 * 1_000;
export const TOOL_OUTPUT_TOMBSTONE_TTL_MS = 7 * 24 * 60 * 60 * 1_000;
export const TOOL_OUTPUT_CLEANUP_INTERVAL_MS = 60 * 60 * 1_000;
export const TOOL_OUTPUT_STALE_TEMP_MS = 60 * 60 * 1_000;

export const TOOL_OUTPUT_READ_DEFAULT_RECORDS = 200;
export const TOOL_OUTPUT_READ_MAX_RECORDS = 1_000;
export const TOOL_OUTPUT_READ_MAX_BYTES = 50 * 1024;

export const TOOL_OUTPUT_SEARCH_DEFAULT_MATCHES = 50;
export const TOOL_OUTPUT_SEARCH_MAX_MATCHES = 100;
export const TOOL_OUTPUT_SEARCH_MAX_BYTES = 50 * 1024;
export const TOOL_OUTPUT_SEARCH_SNIPPET_MAX_BYTES = 1 * 1024;
export const TOOL_OUTPUT_SEARCH_PATTERN_MAX_BYTES = 1 * 1024;
export const TOOL_OUTPUT_SEARCH_TIMEOUT_MS = 5_000;
export const TOOL_OUTPUT_FAMILY_LEASE_TTL_MS = 5 * 60 * 1_000;
export const TOOL_OUTPUT_FAMILY_LEASE_MAX_REFS = 10_000;
export const TOOL_OUTPUT_FAMILY_LEASE_MAX_GLOBAL = 64;
export const TOOL_OUTPUT_FAMILY_LEASE_MAX_PER_FAMILY = 8;
export const TOOL_OUTPUT_FAMILY_LEASE_MAX_PINNED_REFS = 40_000;

export const TOOL_OUTPUT_CAPTURE_QUEUE_MAX_BYTES = 64 * 1024;
export const TOOL_OUTPUT_CAPTURE_QUEUE_WAIT_MS = 1_000;
export const TOOL_OUTPUT_CAPTURE_FINALIZE_WAIT_MS = 5_000;

export const TOOL_OUTPUT_REF_BYTES = 16;
export const TOOL_OUTPUT_REF_LENGTH = 22;
export const TOOL_OUTPUT_CURSOR_MAX_BYTES = 8 * 1024;
export const TOOL_OUTPUT_METADATA_MAX_BYTES = 64 * 1024;
